sonar.organization=jbcom
sonar.projectKey=jbcom_asset-fetch
sonar.projectName=asset-fetch
sonar.sources=src
sonar.tests=tests
sonar.exclusions=dist/**,docs/**,examples/**
sonar.test.inclusions=tests/**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
